<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Aluno</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>
    <form action="/aluno/" method="get">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="/inicio/">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link active" href="/aluno/">Aluno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="/coordenacao/">Coordenação</a>
                        </li>
                    </div>
                    <span class="navbar-text">
                        <a href="/sair/">Sair</a>
                    </span>
                </div>
            </nav>
            <div class="col-12">
                <a href="/inicio/" class="btn btn-secondary mt-5 mb-5 text-center">Página principal</a>
            </div>
            <div class="col-12">
                <div class="col-6 float-left">
                    <div class="card float-left mr-1 mb-1" style="width: 13rem;">
                        <img src="../gray_color_background_145047_300x300.jpg" class="card-img-top" alt="Imagem" style="height: 100px; width: 100px;">
                        <div class="card-body">
                            <h5 class="card-title">Certificado 1</h5>
                        </div>
                    </div>
                    <div class="card float-left ml-1 mb-1" style="width: 13rem;">
                        <img src="../gray_color_background_145047_300x300.jpg" class="card-img-top" alt="Imagem" style="height: 100px; width: 100px;">
                        <div class="card-body">
                            <h5 class="card-title">Certificado 2</h5>
                        </div>
                    </div>
                    <div class="card float-left mt-1 mr-1" style="width: 13rem;">
                        <img src="../gray_color_background_145047_300x300.jpg" class="card-img-top" alt="Imagem" style="height: 100px; width: 100px;">
                        <div class="card-body">
                            <h5 class="card-title">Certificado 3</h5>
                        </div>
                    </div>
                    <div class="card float-left mt-1 ml-1" style="width: 13rem;">
                        <img src="../gray_color_background_145047_300x300.jpg" class="card-img-top" alt="Imagem" style="height: 100px; width: 100px;">
                        <div class="card-body">
                            <h5 class="card-title">Certificado 4</h5>
                        </div>
                    </div>
                </div>
                <div class="col-6 float-left">
                    <table class="table table-dark">
                        <thead>
                            <tr>

                                <th scope="col">Evento</th>
                                <th scope="col">Data</th>
                                <th scope="col">Tipo</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($eventos as $key => $evento) {
                                echo '<tr>';
                                echo '<td scope="row">' . $evento['nome_evento'] . '</td>';
                                echo '<td scope="row">' . $evento['data_evento'] . '</td>';
                                echo '<td scope="row">' . $evento['tipo_evento'] . '</td>';
                                echo '</tr>';
                            }



                            ?>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </form>
</body>

</html>