<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coordenação</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>
    <form action="/coordenacao/" method="get">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark rounded-bottom">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="/inicio/">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link" href="/aluno/">Aluno</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-item nav-link active" href="/coordenacao/">Coordenação</a>
                        </li>
                    </div>
                    <span class="navbar-text">
                        <a href="/sair/">Sair</a>
                    </span>
                </div>
            </nav>
            <div class="col-12">
                <a href="/inicio/" class="btn btn-secondary text-center mt-5 mb-5">Página principal</a>
                <a href="/cadastrarEvento/" class="btn btn-secondary text-center mt-5 mb-5">Cadastrar evento</a>
                <a href="/gerarCertificado/" class="btn btn-secondary text-center mt-5 mb-5">Gerar certificado</a>
            </div>
            <div class="col-12">
                <div class="col-6 float-left">
                    <table class="table table-dark mt-5 mb-5">
                        <thead>
                            <tr>
                                <th scope="col">Eventos marcados</th>
                                <th scope="col">Data</th>
                                <th scope="col">Local</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($eventos_todos as $key => $evento) {

                                echo '<tr>';
                                echo '<td scope="row">' . $evento['nome_evento'] . '</td>';

                                echo '<td scope="row">' . $evento['data_evento_inicio'] . '</td>';

                                echo '<td scope="row">' . $evento['data_evento'] . '</td>';

                                echo '<td scope="row">' . $evento['tipo_evento'] . '</td>';
                                echo '</tr>';
                            }

                            ?>

                        </tbody>
                    </table>
                </div>
                <div class="col-6 float-left">
                    <table class="table table-dark mt-5 mb-5">
                        <thead>
                            <tr>
                                <th scope="col">Eventos que cadastrei</th>
                                <th scope="col">Data</th>
                                <th scope="col">Tipo</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            foreach ($eventos as $key => $evento) {

                            ?>
                                <tr>
                                    <td scope="row"><?php echo $evento['nome_evento']; ?></td>
                                    <td scope="row"><?php echo $evento['data_evento_inicio']; ?></td>
                                    <td scope="row"><?php echo $evento['tipo_evento']; ?></td>
                                </tr>
                            <?php } ?>


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </form>
</body>

</html>